### ISSUE TITLE
RX V581 zone naming issue — no zone discovery

### ISSUE THREAD

**Issue by diplix** [wuub/rxv#37]
the rx v581 seems to have a strange naming pattern for it’s zone b:

`<Menu Func="Unit" Title_1="System" YNC_Tag="System">`
...
`<Menu Func="Subunit" Title_1="Main Zone" YNC_Tag="Main_Zone">`
…
`<Menu Func="Subunit" Title_1="Zone B" YNC_Tag="Main_Zone">`

basically the `YNC_Tag` that is used by `rxv` to determine zones is the same for the main zone and zone b, they can only be identified by `Title_1`. for zone discovery to work for the rx v581 there’s probably adjustments to be made. i’d be glad to test those changes, if someone with better programing skills then myself would be willing to implement thise changes.

this is how the receiver describes itself:
[rx v581 desc.xml](https://gist.github.com/diplix/f8b1b7abacca5856f0e2dd587c7d29b1)

**Comment by diplix** [comment]
of course changing zone discovery to `Title_1` doesn’t help at all, since, i guess, addressing `Zone B` doesn’t really work. however yamaha themselfes figured out a way of displaying both zones and also addressing them separatly. this is a screenshot from the MusicCast app, that correctly identifies both zones of the RX V581 and let’s me turn off and on both separatly, while rxv displays both with exactly the same attributes.
![img_9666](https://cloud.githubusercontent.com/assets/4541494/22729036/326f493a-ede1-11e6-9816-8eb8f103cea0.jpg)
<img width="1158" alt="bildschirmfoto 2017-02-08 um 09 29 31" src="https://cloud.githubusercontent.com/assets/4541494/22729045/3eee133a-ede1-11e6-81a2-74a4c4c1f2eb.png">

**Comment by diplix** [comment]
[i worked around the issue](https://community.home-assistant.io/t/working-around-mafunctioning-zone-b-discovery-for-yamaha-rx-v581-receiver/12830) with two home assistant command line switches.

```
- platform: command_line
  switches:
    yamaha_zone_1_power:
      command_on: 'curl -d "<YAMAHA_AV cmd=\"PUT\"><Main_Zone><Power_Control><Power>On</Power></Power_Control></Main_Zone></YAMAHA_AV>" http://192.168.1.73/YamahaRemoteControl/ctrl'
      command_off: 'curl -d "<YAMAHA_AV cmd=\"PUT\"><Main_Zone><Power_Control><Power>Standby</Power></Power_Control></Main_Zone></YAMAHA_AV>" http://192.168.1.73/YamahaRemoteControl/ctrl'
      command_state: 'curl -d "<YAMAHA_AV cmd=\"GET\"><Main_Zone><Basic_Status>GetParam</Basic_Status></Main_Zone></YAMAHA_AV>"  http://192.168.1.73/YamahaRemoteControl/ctrl | xmllint --format --noent --xpath "//Power/text()" -'
      value_template: '{{ value == "On" }}'
      friendly_name: Yamaha Zone 1
    yamaha_zone_2_power:
      command_on: 'curl -d "<YAMAHA_AV cmd=\"PUT\"><Main_Zone><Power_Control><Zone_B_Power>On</Zone_B_Power></Power_Control></Main_Zone></YAMAHA_AV>" http://192.168.1.73/YamahaRemoteControl/ctrl'
      command_off: 'curl -d "<YAMAHA_AV cmd=\"PUT\"><Main_Zone><Power_Control><Zone_B_Power>Standby</Zone_B_Power></Power_Control></Main_Zone></YAMAHA_AV>" http://192.168.1.73/YamahaRemoteControl/ctrl'
      command_state: 'curl -d "<YAMAHA_AV cmd=\"GET\"><Main_Zone><Basic_Status>GetParam</Basic_Status></Main_Zone></YAMAHA_AV>"  http://192.168.1.73/YamahaRemoteControl/ctrl | xmllint --format --noent --xpath "//Zone_B_Power_Info/text()" -'
      value_template: '{{ value == "On" }}'
      friendly_name: Yamaha Zone 2
```
